### ISSUE TITLE
not working.... help me

### ISSUE THREAD

**Issue by deokju** [Ketho/vscode-wow-api#100]
hello~ my friend!
is not working.....

![image](https://github.com/Ketho/vscode-wow-api/assets/16514143/61aed827-c4ab-4b9d-8422-6c1d27b7a903)

I need code intellisence ...
but do not working...

what should i do??

**Comment by lssdo12** [comment]
The same problem，cannot  Jump to the definition when using the C_BattleNet function, but can jump to the definition  when using the UIParent

**Comment by Ketho** [comment]
Sorry for not responding, this should be fixed in v0.9.11 thanks to #101
