### ISSUE TITLE
Minor: SetCursor parameter should be optional

### ISSUE THREAD

**Issue by Arxareon** [Ketho/vscode-wow-api#117]
Hey!

I found a minor annotation error, the "cursor" parameter for the API function `SetCursor` should be optional.

I changed line 1278 in API4.lua to (and updated the [wiki page](https://warcraft.wiki.gg/wiki/API_SetCursor):
```
---@param cursor? string
```

🫰

**Comment by Ketho** [comment]
Oh, thanks. Is that an explicit nil or can it just be omitted?
The extension should pick it up in the next update.

**Comment by Arxareon** [comment]
Never mind, it *does* have to be an explicit nil.
I just tested it again. When it was pushed to in-game testing I was actually passing nil through a variable to it so I didn't notice.

I'll revert back the wiki changes if I can (I saw you added the brackets I left out).
