### ISSUE TITLE
C_NamePlate.GetNamePlates is missing return type

### ISSUE THREAD

**Issue by emmericp** [Ketho/vscode-wow-api#122]
The wiki page has the return type, so not sure where/how this is going wrong: https://warcraft.wiki.gg/wiki/API_C_NamePlate.GetNamePlates?action=edit

**Comment by Ketho** [comment]
C_NamePlate is kind of annoying since it's lacking documentation in Blizzard_APIDocumentationGenerated

I have manually annotated it on the wiki page and added the NameplateBase type
```lua
<!-- emmylua
---@param isSecure? boolean
---@return NameplateBase nameplates
function C_NamePlate.GetNamePlates(isSecure) end
-->
```

**Comment by emmericp** [comment]
thank you!
