### ISSUE TITLE
How to deal with fields of not implemented templates?

### ISSUE THREAD

**Issue by selfaddicted** [Ketho/vscode-wow-api#126]
I'm working on a scroll frame. scroll bar is not an essential property of scroll frames so there is a constant warning of unidentified field for scroll bars. How can I deal with this? I'm kinda obsessive so can't bear with it lol

**Comment by Ketho** [comment]
You uhh either need to annotate the fields yourself with `@field` or disable the diagnostic for the warning like with `@diagnostic disable-next-line`.

Supporting templates is something I want to do but can't really say when.

**Comment by selfaddicted** [comment]
Thank you. I had no clue where to begin with.
