### ISSUE TITLE
(Request) Feature to display all deprecated code in project

### ISSUE THREAD

**Issue by Xruptor** [Ketho/vscode-wow-api#152]
I think it would be great to have a tool that works in combination with this wonderful API plugin that allows us to see all the currently deprecated code in the project.  It can be shown in a list or if this can't be done at least use strikethrough to display it as deprecated.   That way we can go in and update it accordingly instead of navigating it manually or waiting on bug reports.

**Comment by Ketho** [comment]
I had actually removed the Blizzard_Deprecated addons for the 11.0.2 update. I will keep them back in then for another patch at least if that helps. https://github.com/Ketho/vscode-wow-api/tree/dev/Annotations/Blizzard_Deprecated

Those would show the `Lua Diagnostics.Deprecated` warning as well as the strikethrough.

**Comment by Ketho** [comment]
Deprecations will be kept until patch 11.1.0
