### ISSUE TITLE
Please consider rolling back the latest release with the new settings configuration

### ISSUE THREAD

**Issue by emmericp** [Ketho/vscode-wow-api#159]
Looks like the latest version writes some LuaLS config to .vscode/settings.json, looks like it added this:

```
"Lua.runtime.version": "Lua 5.1",
	"Lua.runtime.builtin": {
		"basic": "disable",
		"debug": "disable",
		"io": "disable",
		"math": "disable",
		"os": "disable",
		"package": "disable",
		"string": "disable",
		"table": "disable",
		"utf8": "disable"
	},
	"Lua.workspace.library": [
		"~\\.vscode\\extensions\\ketho.wow-api-0.16.4\\Annotations"
	]
```

This is pretty annoying because:

1) it completely overrides my user settings.json, I noticed when my library path broke
2) i don't want to disable these built-ins, I have code "normal" Lua code inside my repos beside WoW-specific code (tests and scripts)

I saw there is an option to control whether this goes to user settings or workspace settings, so I tried to change it to user settings, hoping that I can at least override it, but

1) it completely deleted my existing library path setting and replaced it with only its own path
2) the Lua.runtime.builtin option gets overriden on startup even if I change it by hand.

Unfortunately that makes it completely unusable for me, please consider rolling back the release. What was wrong with it just adding itself to user settings?

**Comment by emmericp** [comment]
And for anyone else affected: disable auto-updates and select "install specific version" from the context menu in the extension overview. `0.14.2` seems good

**Comment by emmericp** [comment]
There is also an extra annoying behavior that turns everything into a mess even when using an old version:

All workspaces that I had opened with the new version got the new path that's missing mine added to their local .vscode/settings.json. Now every time I open one of these workspaces that got this upgrade even the old version messes up adding the path: it takes the path from .vscode/settings.json (which is just itself), and updates it and writes it (as the old version did) to my user settings -- completely deleting all other paths I already had in there.

Please don't ever update a user config file based on some kind of derived data, instead load the data from the config file, change it, and write it back.

**Comment by Ketho** [comment]
First of all, I want to apologize for messing up the workspace/user settings.json. I thought when I added an option for choosing the configuration scope it would solve the problem.

In `0.16.0` it briefly changed the user settings.json by default, which was a mess up from me. It should no longer be editing the user setting.json if the option is set to workspace.

> 1. it completely overrides my user settings.json, I noticed when my library path broke
> 2. i don't want to disable these built-ins, I have code "normal" Lua code inside my repos beside WoW-specific code (tests and scripts)

So you have normal Lua code and WoW-specific code in the same repo? I didn't think of that situation and might have to add an option for not forcibly setting `Lua.runtime.version` and `Lua.runtime.builtin`.

When rollbacking to version <=0.14.2 I would've assume it only updated its own config, instead of deleting all other paths in there. But apparently it does.

I actually have a lot of questions so please don't mind if I ask them via Discord to be able to chat directly.

**Comment by emmericp** [comment]
> So you have normal Lua code and WoW-specific code in the same repo?

Yes, e.g., parts of tests that run outside of WoW.

> and might have to add an option

I would really prefer an option to make it not mess with *any* settings except adding the path since that can't be avoided. But that path diff should be based on the existing config, not on some derived and merged config. I believe a big part of the problem is that it adds a single-entry path to some previously empty file with a higher precedence. Then later if you switch the option it uses the file it previously added as source of truth and messes up what the other file already had.

> I actually have a lot of questions so please don't mind if I ask them via Discord to be able to chat directly.

Sure

**Comment by Ketho** [comment]
So there are a few issues:
- There's a [bug](https://github.com/Ketho/vscode-wow-api/blob/0.16.4/src/luals.ts#L90-L97) where the extension reads the workspace version of `Lua.workspace.library` and then writes it to the user `settings.json` if the Configuration Scope option is set to User.

- If there is normal Lua code (e.g. for tooling) and WoW Lua code in the same workspace it's problematic and the extension should not forcibly set `Lua.runtime.version` and `Lua.runtime.builtin`. Having an option to not do that would be nice.
