### ISSUE TITLE
Child Frames/Fields

### ISSUE THREAD

**Issue by ChrisKader** [Ketho/vscode-wow-api#16]
I noticed that child frames or fields created by default when some Frame Types are created are not included in the type defs.

Example would be:

```lua
local f = CreateFrame("CheckButton", nil, UIParent)
```

If I reference `f.text` I am told by the extension in VSCode that it is an undefined field. However, `.text` is created as a FontString at the root of `f` and is the text that is attached to the button. The only way I have found around this is to define a custom class, like shown below, that extends the default class to include the field.

```lua
---@class CheckButton_E : CheckButton
---@field text FontString
local f = CreateFrame("CheckButton", nil, UIParent)
f.text:SetText("Test")
```

**Comment by Ketho** [comment]
Do you mean the CheckButton frame type has a `text` field by default? But `/dump CreateFrame("CheckButton").text` returns nil for me. Or are you using some kind of inherited template?

Note that EmmyLua class inheritance is currently kinda broken (see `https://github.com/sumneko/lua-language-server/issues/660`

**Comment by ChrisKader** [comment]
Looks like .text does come from an inherited template, my apologies.

**Comment by Ketho** [comment]
So something like #15, although I don't really know a solution for that

**Comment by ChrisKader** [comment]
You are right, my apologies for opening a duplicate. I will look at 15 and see what can possibly be done. I am familiar with typescript but I think the limitations of EmmyLua may not easily allow for it :(
