### ISSUE TITLE
Undefined documentations since last updates

### ISSUE THREAD

**Issue by Arxareon** [Ketho/vscode-wow-api#163]
Hi!

Definitions for script objects like "Frame" or Button" and certain aliases are now missing. I haven't seen details about this in the changelog so it might be something to do with smneko's Lua server again or the API has changed so much since TWW, not sure.
![image](https://github.com/user-attachments/assets/27fd3495-fff7-4461-bc9f-e29a6c309125)
![image](https://github.com/user-attachments/assets/89d64a24-efce-4ddb-974b-eb4c6da43886)

Update: I suspect it's an issue with LuaLS, as even descriptions that would come from the AIP like references to "CreateFrame" don't work. at all. Unfortunately I don't have time to dig deeper into it, but I'm using all of the latest extension and vscode versions.
![image](https://github.com/user-attachments/assets/27ee13a0-28ef-4a55-80dc-2a304cf272b4)

**Comment by Ketho** [comment]
What does your settings.json look like?

**Comment by Arxareon** [comment]
![image](https://github.com/user-attachments/assets/665809f3-7b7b-4afa-9244-1b02c19ebf72)
![image](https://github.com/user-attachments/assets/5ce6cbc2-1299-45a3-92fa-cbdd087a78f3)
It was the path. I did see a comment about in the change notes about ~ working on windows as well ass Linux, so there might be some kind of issue with the update messing up existing path definitions with the new addition of the root, inserting it in the front instead of replacing the drive letter. _I checked, however, and `~\…` as path doesn't work, I still need the drive letter but maybe my syntax is wrong._

(I also renamed AnchorPoint to FramePoint as its name has changed as I can see.)

**Comment by Ketho** [comment]
Should be fixed now, I didn't know you could have the extension in a different path than `%USERPROFILE%`

**Comment by Arxareon** [comment]
> Should be fixed now, I didn't know you could have the extension in a different path than `%USERPROFILE%`

Oh, right! It's probably because I have redefined the extension path to be on a different drive. You can do that by appending "extensions-dir" to a custom shortcut like so: `"D:\Program Files\Microsoft VS Code\Code.exe" --extensions-dir="D:\Visual Studio Code\Extensions"` That's why it's not there. If opened via this shortcut, visual studio will grab extension data from the defined path but when opened any other way,, it won't se these extensions as it'll try to look in the default folder.

Funny edge-case. :)
