### ISSUE TITLE
IntelliSense broken

### ISSUE THREAD

**Issue by lenroc-dev** [Ketho/vscode-wow-api#165]
I lost IntelliSense in VSCode with 0.16* and 0.17* versions.  Downgrading to 0.15.9 fixed the issue for me.

**Comment by Ketho** [comment]
uhm what does your workspace and/or user path for `Lua.workspace.library` look like?

**Comment by lenroc-dev** [comment]
I should mention that I'm new to VSCode so, I'm not quite sure how to provide the worspace/path info requested, but the workspace containing the lua file is trusted, if that matters.

In case, it helps..  I've noticed that IntelliSense works for some functions but not others...  for example, get GetItemCooldown IntelliSense works fine, but PickupContainerItem does not.  When I hover mouse over PickupContainerItem, I get "(global) PickupContainerItem: unknown"

**Comment by Ketho** [comment]
Were you able to find a solution to the issue? I've not heard any similar reports yet

**Comment by lenroc-dev** [comment]
It's still flaky. Certain functions seem to work fine and others don't.

**Comment by Ketho** [comment]
Are you using [Multi-root Workspaces](https://code.visualstudio.com/docs/editor/multi-root-workspaces)?

Can you show me your settings.json? You can open it with the "Open Workspace Settings" command

![image](https://github.com/user-attachments/assets/133e80c7-e0c2-438c-bf27-14c48ee4e01e)

**Comment by AmsTaFFix** [comment]
same problem, reverted to 0.15.9 too. when i made an update my settings.json has been changerd 
![image](https://github.com/user-attachments/assets/39cf1c05-01ec-4742-82d4-a77a40b650b0)
[settings.json](https://github.com/user-attachments/files/16828734/settings.json)

**Comment by AmsTaFFix** [comment]
ohhh, after installation of 0.15.9, and the update to last version it started working

**Comment by lenroc-dev** [comment]
Seems to start working after upgrading to latest today.
