### ISSUE TITLE
The second params of `EJ_GetEncounterInfoByIndex ` should be optional

### ISSUE THREAD

**Issue by gjfLeo** [Ketho/vscode-wow-api#166]
According to [FrameXML](https://www.townlong-yak.com/framexml/live/Blizzard_EncounterJournal/Blizzard_EncounterJournal.lua#839) and [Warcraft Wiki](https://warcraft.wiki.gg/wiki/API_EJ_GetEncounterInfoByIndex), the second params of `EJ_GetEncounterInfoByIndex ` should be optional.

**Comment by Ketho** [comment]
Thanks for spotting that
