### ISSUE TITLE
Font Flags: "THICK" or "THICKOUTLINE"?

### ISSUE THREAD

**Issue by cjhwang0222** [Ketho/vscode-wow-api#171]
https://warcraft.wiki.gg/wiki/API_FontInstance_SetFont

wiki says "THICKOUTLINE" but the extension says "THICK", which leads to 'param-type-mismatch' error

**Comment by Ketho** [comment]
This has been fixed in https://github.com/Ketho/vscode-wow-api/commit/d9f07bae0e1509000ca6868cb06853a09b71999a but I have not pushed a release yet, sorry
