### ISSUE TITLE
wasteful updates of "Lua.workspace.library"

### ISSUE THREAD

**Issue by cjhwang0222** [Ketho/vscode-wow-api#172]
I'm creating my addon switching between Mac and Windows.
The thing is, "Lua.workspace.library" is updated based on current OS, which leads to wasteful updates in `settings.json` for `vscode` and triggers changes in git status. How can I resolve this?

**Comment by Ketho** [comment]
I see switching between different OSes would be annoying for the settings. You could change it to User settings so it will not use the Workspace settings.json for that

https://github.com/Ketho/vscode-wow-api/wiki/Settings#configuration-scope

![image](https://github.com/user-attachments/assets/00d724c3-157d-48fc-a25f-a66e93d6f0bf)

**Comment by cjhwang0222** [comment]
thanks for the tips
