### ISSUE TITLE
Missing ruRU in GlobalStrings locale option

### ISSUE THREAD

**Issue by Nightwarden24** [Ketho/vscode-wow-api#26]
**Description**
There is no ruRU in the drop-down list of GlobalStrings locale option.

![](https://i.imgur.com/i5jd8xz.png)

**Solution**
Compare these two lists:
- https://github.com/Ketho/vscode-wow-api/blob/master/Lua/ToTypeScript/GlobalString.lua#L14
```lua
local locales = {
	"deDE",
	"enUS", -- same as enGB
	"esES", "esMX",
	"frFR",
	"itIT",
	"koKR",
	"ptBR", -- same as ptPT
	"ruRU",
	"zhCN",	"zhTW",
}
```
- https://github.com/Ketho/vscode-wow-api/blob/master/package.json#L65
```json
"wowAPI.locale": {
	"type": "string",
	"default": "enUS",
	"enum": [
		"enUS",
		"deDE",
		"esES",
		"esMX",
		"frFR",
		"itIT",
		"koKR",
		"ptBR",
		"zhCN",
		"zhTW"
	],
	"markdownDescription": "Sets the GlobalStrings locale for code completion and hover."
}
```

**Comment by Ketho** [comment]
Oh my bad, thanks for spotting that :S
