### ISSUE TITLE
Unknown references through addon namespaces

### ISSUE THREAD

**Issue by Arxareon** [Ketho/vscode-wow-api#31]
Hey!

I'm communicating between different files of my addons through the provided addon namespaces. Previously, annotations and references were pulled through the namespace so I could Ctrl+click to jump to a function shared in the namespace from one file to another or I could see the EmmyLua annotation on a function defined in another file for instance.

_More specifically, I use a global table shared between addons, which contains subtables with version keys. A specific key is shared in the addon namespace so all files of the addon can access the specific subtable of that global table with that key (if multiple addons are on the same version, they can access the same subtable with the identical key - that's the idea in a nutshell)._ 

Now, this functionality is broken. I'm not sure if it was broken by the main Lua extension of sumneko or WoW API specifically.

### Example:
Code in file 1:
```
--Addon identifier name, namespace table
local addonNameSpace, ns = ...

--This is a hello
ns.Hello = function() end

--This is a global hello
Hello = function() end
```

Code in file 2:
```
--Addon identifier name, namespace table
local addonNameSpace, ns = ...

ns.Hello()

Hello()
```
Annotation and jump to definition doesn't work when it's through the namespace table:
![image](https://user-images.githubusercontent.com/33066061/165970948-660b9c0d-01a2-4e33-a69a-f8e276cb63e3.png)

Annotation and jump to definition does work when it's global (as it did previously with the namespace as well):
![image](https://user-images.githubusercontent.com/33066061/165972447-14becde1-c5c8-4751-8a4b-f13287131fc7.png)

It might be related to this issue, I'm not sure: https://github.com/Ketho/vscode-wow-api/issues/28#issue-1186909229

**Comment by Ketho** [comment]
This is indeed a pretty glaring issue. The addon namespace appears to be properly supported by [IntelliJ EmmyLua](https://plugins.jetbrains.com/plugin/9768-emmylua) but not in Sumneko's implementation.

As in you can only define it once with `---@class` and all the other files with `---@type` can only read from it.

file1.lua
```lua
---@class ns
local _, ns = ...
ns.test = "banana"
```
file2.lua
```lua
---@type ns
local _, ns = ...
ns.hello = "world"
```
file3.lua
```lua
---@type ns
local _, ns = ...

print(ns.test)
print(ns.hello)
```
![image](https://user-images.githubusercontent.com/1073877/166169160-961350b3-a4ef-4824-9074-0d1d7b019543.png)

I will need to make another issue for Sumneko to support this behavior.

**Comment by Arxareon** [comment]
Thanks for looking into it & for letting Sumneko know!
Not sure what was changed or exactly when, but it definitely was working before.

**Comment by Arxareon** [comment]
_A suggestion for anyone who have a hard time with this issue:_
**A temporary solution is to roll back Sumneko's Lua extension to version 2.6.8 for the time being.**
![image](https://user-images.githubusercontent.com/33066061/170099495-c5a644d8-d17a-4345-850f-ce8686265a1f.png)
![image](https://user-images.githubusercontent.com/33066061/170099514-fb12500e-8360-4a6e-b517-5958b7f36d86.png)

**Comment by Ketho** [comment]
I'll paste the solution Sumneko gave: using `@class` multiple times (when you need to make it mutable).
- file1.lua
```lua
---@class ns
local _, ns = ...
ns.foo = "bar"
```
- file2.lua
```lua
---@class ns
local _, ns = ...
ns.fruit = "banana"
```

**Comment by Ketho** [comment]
> I could just revert to 2.6.8 and continue using that, but what my question is, **how could I restore this functionality for the structure I built?**

I honestly have no idea, this is way over my head. That would be question for Sumneko, and I suppose you would have to keep using 2.6.8 otherwise.
