### ISSUE TITLE
CreateFrame <T> undefined fields

### ISSUE THREAD

**Issue by mrbuds** [Ketho/vscode-wow-api#39]
```Lua
local frame = CreateFrame("FRAME");
frame:RegisterEvent("PLAYER_ENTERING_WORLD");
frame:SetScript("OnEvent", HandleEvent);
...
```
(field) FRAME.RegisterEvent: unknown
(field) FRAME.RegisterUnitEvent: unknown
(field) FRAME.SetScript: unknown
(field) FRAME.GetScript: unknown
(field) FRAME.SetAllPoints: unknown
(field) FRAME.SetPoint: unknown
(field) FRAME.UnregisterEvent: unknown
(field) FRAME.Hide: unknown
(field) FRAME.Show: unknown
(field) FRAME.EnableMouse: unknown
(field) FRAME.SetPoint: unknown
(field) FRAME.SetHeight: unknown
(field) FRAME.SetWidth: unknown
(field) FRAME.SetSize: unknown
(field) FRAME.CreateTexture: unknown
(field) FRAME.CreateFontString: unknown
(field) FRAME.SetClipsChildren: unknown
(field) FRAME.OnSizeChanged: unknown
(field) FRAME.SetRotatesTexture: unknown
(field) FRAME.HookScript: unknown
(field) FRAME.SetMovable: unknown
(field) FRAME.SetResizable: unknown
(field) FRAME.SetMinResize: unknown
(field) FRAME.width: unknown
(field) FRAME.height: unknown

```Lua
local hsvFrame = CreateFrame("Colorselect")
hsvFrame:SetColorRGB(r1, g1, b1)
hsvFrame:SetColorHSV(h3, s3, v3)
```
(field) Colorselect.GetColorRGB: unknown
(field) Colorselect.GetColorHSV: unknown
(field) Colorselect.SetColorRGB: unknown
(field) Colorselect.SetColorHSV: unknown

```Lua
local cooldown = CreateFrame("COOLDOWN", "WeakAurasCooldown"..frameId, region, "CooldownFrameTemplate");
```
(field) COOLDOWN|CooldownFrameTemplate.SetDrawBling: unknown
(field) COOLDOWN|CooldownFrameTemplate.SetFrameLevel: unknown
(field) COOLDOWN|CooldownFrameTemplate.SetAllPoints: unknown

```Lua
local border = CreateFrame("frame", nil, region, BackdropTemplateMixin and "BackdropTemplate")
```
(field) BackdropTemplate|frame.SetFrameLevel: unknown

```Lua
local popupFrame = CreateFrame("EditBox", "WADebugEditBox", UIParent)
```
(field) EditBox.SetFontObject: unknown

```Lua
local scrollFrame = CreateFrame("ScrollFrame", "WADebugEditBoxScrollFrame", UIParent, "UIPanelScrollFrameTemplate")
```
  :SetMovable
  :SetFrameStrata
  :SetSize
  :SetPoint
  :SetHitRectInsets
  :SetScrollChild
  :StartMoving
  :StopMovingOrSizing
  :GetLeft, GetTop etc..
  :Hide

Textures:

![image](https://user-images.githubusercontent.com/189656/169913085-6c0b62b1-ece4-445b-888f-fb107d0ef89e.png)
![image](https://user-images.githubusercontent.com/189656/169913129-ddb0ce65-bf6e-4e89-a30c-80c4cf9253f2.png)

**Comment by Ketho** [comment]
```lua
local hsvFrame = CreateFrame("Colorselect")
```
Frame types are case sensitive (the language server sees it as a class), so you need it to change it to `ColorSelect` or make it full lowercase/uppercase
