### ISSUE TITLE
Global functions not known

### ISSUE THREAD

**Issue by Nils89** [Ketho/vscode-wow-api#4]
Some global functions are not known:
GetUnitName:
![Bildschirmfoto 2021-03-21 um 18 35 25](https://user-images.githubusercontent.com/23194902/111914913-45fd4e00-8a74-11eb-9954-be570a780ccc.png)

UIFrameFadeIn
![Bildschirmfoto 2021-03-21 um 18 42 23](https://user-images.githubusercontent.com/23194902/111915173-32061c00-8a75-11eb-92f9-c1fe84af7865.png)

**Comment by Ketho** [comment]
Thanks, added them for the next release
