### ISSUE TITLE
Some missing API's or wrong API parameters

### ISSUE THREAD

**Issue by Nils89** [Ketho/vscode-wow-api#47]
Hi,
thanks for that amazing extension :)

I habe found some API's which requires wrong parameters:
GetActiveSpecGroup() -> the parameter is required but it is optional
GetSpellLevelLearned(spellId) --> Missing
UIFrameFadeIn and UIFrameFadeOut --> required the wrong types tables instead of dbl
UnitBuff() --> first parameter retirees a string not a integer
PlaySoundFile() --> missing
UnitPower() --> has optional parameters
UnitPowerMax() --> has optional parameters
UnitIsMercenary() -- parameter unit = string --> missing
SetSpecialization() --> second parameter is optional
GetAddOnMemoryUsage() --> parameter: index --> missing
GetAddOnCPUUsage() --> parameter: index --> missing

**Comment by Ketho** [comment]
A few of those APIs like [UnitIsMercenary](https://wowpedia.fandom.com/wiki/API_UnitIsMercenary) were not documented yet, but you can help out by creating a wowpedia page and it will be automatically pulled 👍
