### ISSUE TITLE
C_TransmogCollection.GetCategoryCollectedCount category parameter 

### ISSUE THREAD

**Issue by DiscordGregory** [Ketho/vscode-wow-api#49]
The function takes a single parameter of category which is Enum.TransmogCollectionType, this type is a number but in the extension it has the type as TransmogCollectionType. There are a few functions with the TransmogCollectionType as a parameter type 

![image](https://user-images.githubusercontent.com/59945495/186142461-8f3d8eb8-3d8c-4248-a7c9-e560fbccf7b8.png)

**Comment by DiscordGregory** [comment]
Sorry it took me so long to respond, I didn't get a notification to replied :(

![image](https://user-images.githubusercontent.com/59945495/187198256-f7fbcffb-026e-4de0-9424-294b142c4b74.png)

**Comment by Ketho** [comment]
hm thanks, that popped the warning. I will add the number type to enums, something like
```lua
---@param category TransmogCollectionType|number
---@return number count
function C_TransmogCollection.GetCategoryCollectedCount(category) end
```
