### ISSUE TITLE
SetScript second param can be nil

### ISSUE THREAD

**Issue by Stanzilla** [Ketho/vscode-wow-api#56]
When using nil as second param to SetScript you currently get a warning, looks like in https://github.com/Ketho/vscode-wow-api/blob/1fea0434899666e194c8a18eeb2cbff3bde4a713/EmmyLua/API/Widget/Abstract/ScriptObject.lua#L25 you defined that though.

![image](https://user-images.githubusercontent.com/75278/199773660-16c6ad06-9116-439c-b871-0877595805a8.png)

Not sure what's up

**Comment by Ketho** [comment]
Yeah, I haven't pushed a release yet with the new emmylua changes. It has been a while 😓

**Comment by Ketho** [comment]
yay for a new release
