### ISSUE TITLE
UIFrameFadeOut and UIFrameFadeIn wrong parameter types

### ISSUE THREAD

**Issue by Nils89** [Ketho/vscode-wow-api#65]
---[FrameXML](https://www.townlong-yak.com/framexml/go/UIFrameFadeIn)
--- Convenience function to do a simple fade in
---@param frame Frame
---@param timeToFade table
---@param startAlpha table
---@param endAlpha table
function UIFrameFadeIn(frame, timeToFade, startAlpha, endAlpha) end

---[FrameXML](https://www.townlong-yak.com/framexml/go/UIFrameFadeOut)
--- Convenience function to do a simple fade out
---@param frame Frame
---@param timeToFade table
---@param startAlpha table
---@param endAlpha table
function UIFrameFadeOut(frame, timeToFade, startAlpha, endAlpha) end

should be

---[FrameXML](https://www.townlong-yak.com/framexml/go/UIFrameFadeIn)
--- Convenience function to do a simple fade in
---@param frame Frame
---@param timeToFade number
---@param startAlpha number
---@param endAlpha number
function UIFrameFadeIn(frame, timeToFade, startAlpha, endAlpha) end

---[FrameXML](https://www.townlong-yak.com/framexml/go/UIFrameFadeOut)
--- Convenience function to do a simple fade out
---@param frame Frame
---@param timeToFade number
---@param startAlpha number
---@param endAlpha number
function UIFrameFadeOut(frame, timeToFade, startAlpha, endAlpha) end

**Comment by Ketho** [comment]
Oh dang, I didn't do a proper job in #4
