### ISSUE TITLE
Support for 10.0.2

### ISSUE THREAD

**Issue by ivannpaz** [Ketho/vscode-wow-api#68]
Hey @Ketho !

Are there any plans to add support for DF 10.0.2 in line? Or would that need to be done on a different project?

I got the language server and this plugin to work for most things, but still get some warnings regarding certain globals, e.g.:

![image](https://user-images.githubusercontent.com/16879/209553469-ec180bcb-3c86-47ed-9baf-60c0a7742ac0.png)

Any help here really appreciated!

**Comment by Ketho** [comment]
There are plans to support globals and XML frames (#17), but I haven't really motivated myself to do it yet 🙁

My approach would be to check for the vscode warnings and then dynamically add the emmylua definitions so there would be less of a performance hit.

**Comment by Ketho** [comment]
Should be fixed in the v0.9.1 release
