### ISSUE TITLE
string "questnpc" is not seen as a valid UnitId parameter

### ISSUE THREAD

**Issue by Yttrium-tYcLief** [Ketho/vscode-wow-api#76]
Specifically in my situation I'm using `UnitGUID("questnpc")`. This is valid syntax in every API version since vanilla 1.0. This value [_is_ listed on the Wowpedia article for UnitId](https://wowpedia.fandom.com/wiki/UnitId), so I figured I'd open an issue report for it.

![image](https://user-images.githubusercontent.com/1037011/226950138-ffb95deb-997f-4602-b1e0-caaee7391657.png)

To clarify, this value does *not* always return the exact same target as `npc`, and there are programmatic uses for it.

**Comment by Ketho** [comment]
huh never knew that existed 👀
