### ISSUE TITLE
Any way to get older expansions?

### ISSUE THREAD

**Issue by burner1024** [Ketho/vscode-wow-api#77]
Specifically, I'm interested in coding for vanilla (1.12.1).
Not sure how hard that would be to add.
I see that the [wiki](https://wowpedia.fandom.com/wiki/World_of_Warcraft_API) entries contain "Game Flavors" and "Added in" fields. And there's [vanilla](https://vanilla-wow-archive.fandom.com/wiki/World_of_Warcraft_API) wiki, too.

**Comment by Ketho** [comment]
Unofficial game versions like 1.12.1 won't be supported, sorry

classic_era (1.14.3) would be be nice to support though
